version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12

    pre_build:
        commands:
            - echo Installing dependencies...
            - npm ci
            - npm run lint
    build:
        commands:
            - echo Building...
            - npm run build
    post_build:
        commands:
            - echo Build complete on `date`

artifacts:
    files:
        - '**/*'

    base-directory: build
